Migrating contain matcher
petereon/expycted pull request #83
Opened 2023-02-19 20:25 UTC by tamar-ot

Before submitting this PR, please make sure:

- [ ] My code follows the style guidelines of this project
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Type of change

- [ ] Bug fix *(non-breaking change which fixes an issue)*
- [ ] New feature *(non-breaking change which adds functionality)*
- [ ] Breaking change *(fix or feature that would cause existing functionality to not work as expected)*
- [ ] This change requires a documentation update

2023-02-19 20:28 UTC, tamar-ot commented
'test_method_chaining' get failed, contain matcher definition should be edit.

2023-02-20 05:43 UTC, bdsoha commented
Seems like we can also remove `expycted.internals.utils.assertion`.

2023-02-20 05:54 UTC, tamar-ot commented
right, will be remove.

2023-02-20 06:18 UTC, tamar-ot commented
there is still using of this 'assertion' in  expycted.internals.filesystem. after I will edit this code Its could be remove.

2023-03-01 06:30 UTC, bdsoha requested changes

2023-03-01 06:30 UTC, bdsoha commented on test/unit/matchers/test_contained_in_matcher.py
> +        stubs.SAME_OBJECT,
Use these objects instead:

https://github.com/bdsoha/expycted/blob/641a093067900912833ff71ccc4ae5830a2426c2/test/helpers/stubs.py#L70-L71

2023-03-01 13:13 UTC, bdsoha approved these changes

2023-03-01 13:13 UTC, bdsoha commented
LGTM

2023-03-01 13:15 UTC, merged